language: generic
sudo: required
services: 
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_1b050925b83c_key -iv $encrypted_1b050925b83c_iv -in multi-k8s-278008-6748c672d002.json.enc -out multi-k8s-278008-6748c672d002.json -d
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-278008-6748c672d002.json
  - gcloud config set project multi-k8s-278008
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mkayhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkayhan/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master
